### ISSUE TITLE
Cannot install optimus_cli due to multiple errors

### ISSUE THREAD

**Issue by ochubey** [testvagrant/optimus_cli#1]
Getting multiple warnings and errors such as 

> [nodegit] Configuring libssh2.
> { Error: Command failed: /usr/local/lib/node_modules/optimus-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/optimus-cli/node_modules/nodegit/vendor/openssl/openssl
> /usr/local/lib/node_modules/optimus-cli/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
> Try `/usr/local/lib/node_modules/optimus-cli/node_modules/nodegit/vendor/libssh2/missing --help' for more information
> configure: WARNING: 'missing' script is too old or missing
> configure: error: No crypto library found!
> Try --with-libssl-prefix=PATH
>  or --with-libgcrypt-prefix=PATH
>  or --with-wincng on Windows
> 
>     at ChildProcess.exithandler (child_process.js:270:12)
>     at emitTwo (events.js:125:13)
>     at ChildProcess.emit (events.js:213:7)
>     at maybeClose (internal/child_process.js:897:16)
>     at Socket.stream.socket.on (internal/child_process.js:340:11)
>     at emitOne (events.js:115:13)
>     at Socket.emit (events.js:210:7)
>     at Pipe._handle.close [as _onclose] (net.js:549:12)
>   killed: false,
>   code: 1,
>   signal: null,
>   cmd: '/usr/local/lib/node_modules/optimus-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/optimus-cli/node_modules/nodegit/vendor/openssl/openssl' }
> /usr/local/lib/node_modules/optimus-cli/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option

Terminal installation error log: https://gist.github.com/ochubey/9d989782d4d7c4943e2528db3222ab0e
Full installation error logs:https://gist.github.com/ochubey/3891fcd3bcb74097ce41f8c3810815db

**Comment by KrishnB** [comment]
@ochubey This could be becuase of your workstation's libss2 version, can your try with this command `brew install libgcrypt` and try again?
